### ISSUE TITLE
One unit of two from Landscape charm unit stuck in `Waiting on relations: db`

### ISSUE THREAD

**Issue by marceloneppel** [canonical/postgresql-operator#171]
## Steps to reproduce

1. Use the Landscape scalable bundle with two Landscape units and add the following overlay:
```yaml
series: jammy
applications:
  postgresql:
    channel: 14/edge
    charm: ch:postgresql
    num_units: 1
```

## Expected behavior
Units active/idle.

## Actual behavior

One of the Landscape units becomes stuck with the `Waiting on relations: db` message.

## Versions

Operating system: Ubuntu 22.04

Juju CLI: 2.9.43

Juju agent: 2.9.43

Charm revision: 306

LXD: 5.14-7072c7b

## Log output

Juju debug log: 
unit-landscape-server-0: 14:19:53 INFO unit.landscape-server/0.juju-log db:7: %s not in allowed_units

## Additional context

N/A
